function ItemnameToImageData(itemName){
    ImageData = ""
    switch(itemName){
        case "Mashed Potato":
            ImageData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAALCAYAAABLcGxfAAAAAXNSR0IArs4c6QAAAP9JREFUKJFtkT9Lw0AYxn8XXHJTOvgpnIoguGQRih1c/QIudjAVdHTs0kHQLB111cEPEHDJUhAkk65BlHY0BO669XUoOZPTgxfuvXv+vM+dwlv5ZCztPr66Ve1+ywfuJufoMAOzhw0icpA/xHwyFlOXv/XxJPH0UExdysn8SExdinNuwFIV7tIvqQoxdSkX8b4EjYsNItKdtJNHhxl8F9ggcmeOMJyN0OsKHWYkb8lGZDUgWdx1RJQf1i62oddHryunrMOMy4P7jUOT/jW9wa4G0Ou7EYezEQCPZ88AXOdzpf57e4Dl19LtX94/u4Q2qQ30wQCdX3w4PRYf2AYD/ADKdpm+AHVCVAAAAABJRU5ErkJggg=="
            break;
        case "Pumpkin Soup":
            ImageData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAAKCAYAAABi8KSDAAAAAXNSR0IArs4c6QAAANpJREFUGJVtkLGqwkAQRc+mERGFRLAxWIpgZNusKNjaCPkL4T1bv0Ox8R8E9RMsBasgNpaijWAsUtkYC9lFY6YaZs6dOzOCVLSqtUTn+8tJfPZEGppKG+XFPGWAP158iYQGp9IGYOiUmUc3lBeT8x0A5OjK/nISVqtaSyYDZcDuXwHlxfwHTRrLEo9tRDir0Ks3E6HtJwOF33GxwpXZ8SkDrHBFf53HtR3E50FaBNAu7uiv8wC49nudH7hcKJpmOqys4vkeZdbMN9LTtb0Wbo4H8fX0LNHmeDDMC0KfRJXEsg5HAAAAAElFTkSuQmCC";
            break;
        case "Bumpkin Broth":
            ImageData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAKCAYAAACALL/6AAAAAXNSR0IArs4c6QAAAVNJREFUGJVtkb9LQlEYhp9zveX1B+YRCaMoimqxJZqEahKiiCiXmtwcWkKwpaG5qX+hIRByEhycpCHEJqcQoitJQ9hg3RCzmyanQXQIn/l53++FTwAsh6OsT/covjpUKK7zdv3LgFBcZ6XaEYWSxlOlgL4cjmLMCYovDpWP2VxsSq5aLYLSRSpicJa32CkZamO2JyCK2No/pmaaKhTXuflqA+D2OwFoWN8EpYt3u8122sX80pLQaqapEsnkUD7yuAFIRQyC0tWf5fSQSCapmabShmOFxvn2BLmxHgCX9zapiAHA4+TQQgPIZnKkZ06JPXzS/uhfsiwb866LZf1wa5+QzeT6veHVXbodWwWnFjg43GMU2UyORv2ZsXFD6N2ODYA/IIct//EHJI06dDs2OoDXJ0W1UlaL4bWRgWqljNcnRatpIQaP8/okraalRgUG8lOlwB9tDH3Tjcnb2QAAAABJRU5ErkJggg==";
            break;
        case "Boiled Eggs":
            ImageData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAYAAABWdVznAAAAAXNSR0IArs4c6QAAAK5JREFUKJG9zzEOgkAQheF/kUYOQIEHsOEenAAu4+2MWtlZUFIYsdxoNpAAy9gIyoqx83WTfG8mA3+LuGm1zDk1YAD2awC6ssFPC6Qu8YKVei94c3jctoxwLyoRERf7acG3i767dQ4DNPcL1mj8vr7SJ7vpZw7ujh5e8vxhEUTKGo01mtv5MMIJ3myxRmN0jsKJrUrp2v41Gw2A0TlhnKmPAkB1OcmAhoRxNmt/5gFOCoezYAKGfQAAAABJRU5ErkJggg==";
            break;
        case "Kale Stew":
            ImageData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAIBAMAAAA/ygPCAAAAKlBMVEUAAADAy9za2to+iUjXdkPkpnJjx03q1Kq4b1CFqHAmXEKClVlwfkt9gUav75hSAAAAAXRSTlMAQObYZgAAADxJREFUCNdjYGBSUjJjYGAzmeqcrMCgnFzbZdrEoGrl6R6yiUFIpeRIkyKDoJCSkqIgA6MgEAgwAGkgCQAzxgl9sRPy+AAAAABJRU5ErkJggg==";
            break;
        case "Mushroom Soup":
            ImageData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA+m62AAAAAXNSR0IArs4c6QAAANtJREFUGJVtj7FqwlAARc/DZ7HUUchiIIvQxVIQ2izi5qSD4pRRUPADuhZKEbTt6pdYcHbULBYXQZDAA0EUHJpYSy3PQQMOOXCne+ByBWecVkcTQbNeA0B0Xz/4Wh50+X9I6uaaZCIOgL//I+684U5mPDVKQl5KaqAAsJ1bfqtt3MmMtNvDaXW0DCfUQFF8znN1Z/NZe8fmhfttwObci2yuorMPj0RNb4If+rEC0/EICeDNF/QzBdhzSkjs1AFIw7TESnnam0d9hu/tGsO0hNz5AaEcJRqmJXZ+wBHQBVW1QY2vrwAAAABJRU5ErkJggg==";
            break;
        case "Reindeer Carrot":
            ImageData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA8AAAAPCAYAAAA71pVKAAAAAXNSR0IArs4c6QAAARJJREFUKJGNkSFvAjEYhh/Ibo7MERTBHDNb0DMXcoqQnJlGzt9fmN0PIEHg7x9MktshmF1AbLkEMTPEuGRbEKOiiKVNS1qyT37t8z5vU/BMkqUyyVLpOwc4cy2jh4FsdtanOADqLmMYBZSFAKA7iuVs2HM2qB0bL9qXmNayEGyWeybVFoD48UUz2qyMX+9vAMzHO21/vf2mfxcAYLaoK6NahNHfpUm1ZbPck4efusXN1Y8VUEuyVDY7a8pCEEYB8/GO1vU5APdPH9r4+1zpkMWqYdf2GfOpsECzgX58dxRLlzGfCgsw7drsMypIVTXH+qrZsCd9xn/BLsCsvFg19F9b8KkAc7ywK+DY6KztCnAZ1RwA0RyWCxS2vrIAAAAASUVORK5CYII=";
            break;
        case "Kale Omelette":
            ImageData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAYAAABWdVznAAAA8ElEQVQoFWNgGPqAEdkLB07f+Q/i2ytvYohZdZRB3lyUodVgOgMjEMDUsYAYMIWzzxQwLA4QZYhZ+ZpB3pSF4eHJ1wwM8v0M/4EApA6kkQWk+PSFGwzvDeeAFTOy6zK8vrUTiH8z7Kx1Z/j/8zIDw4skht4twWCNYBtAulsePWFgkBYEmr4PrBAkBlYMpGuevmcQBAkAAROEYmDofdvAwHD8MtiW6nuH4IpjN7yGGAZVyNg9e8t/UwMNMBfktGJhoEY0cEh2BYO9iTJDz5ytDGDfgzSB1MA0oqlnABkEAqWpPojgAgnANILYyACkEMYHAD8AX5QNTZZyAAAAAElFTkSuQmCC";
            break;
        case "Cabbers n Mash":
            ImageData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAYAAABWdVznAAAA30lEQVQoFWNgGPqAEdkLz159/M85eQLDMyVphl8v3jCwSYgwCHqHMkiJ8cPVgRkghe+3rgYrYmXnYPjHzcAg+/gdw1MhIYbfP3+ANWolJDMwAgELSPHLudMZFL5+Y3gsK8TwD2gl01cGMBtkOysDB8OzA+8YVqwsZvgPBIwHTt/5ryYvCnbZjPgmhkA7UQZmIQ6Gl8d+MUjqs4FtMKgoB8sfPHOXgbF79pb/pgYaYAGYRhBHUpQPLAYiQAphAKwBxIFpgkngosGeBtmCrACXZgdTFUZ4cKFrQjcApBgkBgDr+1CgnVKDRgAAAABJRU5ErkJggg==";
            break;
        case "Roast Veggies":
            ImageData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAALCAYAAABLcGxfAAAAAXNSR0IArs4c6QAAAXpJREFUKJF9kU8og3EYxz8v77bXCCUpciAH5U27jHbhYPmTi/wpl5VyVFy0w5QclAMXd+Xq+Lohyg4YoTeRKe1gf7LFRGZ7bXt/DsuYg+/p6dvzfJ/n6QP/yHMwLDwHw+K3J30XO3MjAqDfkyN3FGJabeEtLngJm/hiCoPrmgRQBhD0uoXa3Uqv7QoeHslHMyTuC82741Oo3a0EvW4BIAe9blHl6KTO1UW6NgKH55hTy2yFt6lyLpC6XKa+Z4xCMEL+Pikb1bB3jGK2jZJ/0qhUxzA/brHfXDOReKe6QYIBG8UB5eIKOXGPEUhim13hM6ZhPdaRm+1sBYJMOtqpqJEKPwDkhhYxAknKmxQsZ6tYj/WiZ/Q7eQmbLPmNnw1lFkj3OZmV38lmYDN6S+5RwzqzgmIK1vU94AF54zSF2wihAtBEtuaO9Kvg2TECESByCkA8nGRfTyGv+U8kcBXhxBrz+GIK14RKIO7rcdb8J1IR3Hyvq4ToXxWC4Qs6t5wT//wKIwAAAABJRU5ErkJggg==";
            break;
        case "Bumpkin Salad":
            ImageData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAAKCAYAAABi8KSDAAAAAXNSR0IArs4c6QAAAQtJREFUGJVtkDFLw1AUhb/XKB2qSFIo2IQIYhchiEt1sZ0V/BUugiDUwdnZuYKDq0sRBP0BDS1i1rYESutSqZChvIIoxSo+B8mjBu90Lvecc8+9kCjPdpVnu2pyuqqSs7kYHDzuq37jE78w4iOQpCtlJqCK1190Xp4FgIjdzON1CqV5AKq3IQCVxp52vQyqwvBsVxVvNpCDb7IrBlfbd4zzed7EAqUtg6XBMoeb8DCSZymA5sW7diif72rcquUAOGm+4pjWb+Z0/YmINaLOlJ2jDNN2QKuW4z4aAtCVdRzTQni2++fqbGYRx7QAGI4lgO5TyfckSbNC/Y2kIN4QC/1eKMQs4b9Ifi/UnB9QXFkXhlsP9QAAAABJRU5ErkJggg==";
            break;
        case "Goblin's Treat":
            ImageData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAAJCAYAAADkZNYtAAAAAXNSR0IArs4c6QAAAJhJREFUGJVtkLEKwjAQhr8TcRE7FRqHIggdfQ8fOUPfwaF0acGlgxEytbh0qUNJTGpuOrjvO+4/YVMqrxbXG9tLONtvoexeom4HTDODZgklcaCDjsUJgM97Wrc3M6MeMLYXSYGuQoHHbj1j1ANQopj+BAfm5+vv5lBIgQASpgfIiosf2tcz6n3AEAYiCKBra4n+mJK6tvbMF0EbRKiToRY6AAAAAElFTkSuQmCC";
            break;
        case "Cauliflower Burger":
            ImageData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAYAAABWdVznAAAAAXNSR0IArs4c6QAAAO9JREFUKFNjZEACn6+u/M+jFYYsxPDl2iqGxxv3M2hVzWAESYAJhhP2/z/zZjEgKwYphAG2J28Z2PlXMjBYHGRkZOhy/P9TP5SBzS0TLI+sENkqsKaLqxkYkU1HV8x66TjDtZN3GVRTY8B6eT9PY2D8////f2SF6IqQbQE5Ge6kXzLCKJ5F56A4ieEQEwPIH9g0gRSCAMj9kFDqcvzPYPePAaYJ2WSYIrA8CBxigmoAcZAE4WyY7kNMYNa1P+oMjNfaMv4rG+vBrQQ5DW4yVAPMuaAIBEccTBOIDfIHzN0wC0BisNiGxDRUE75ggiUNANzmc70sgR+GAAAAAElFTkSuQmCC";
            break;
        case "Pancakes":
            ImageData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAALCAYAAABLcGxfAAAAAXNSR0IArs4c6QAAAPZJREFUKJFjZEACX091/f/55QayEIOQ0zxGZD6cc2eC4n8GLEBIzxFFExOyYlk7dQblTF2Gv/9/wfG7Q5sZ3u1L+g9Tw4RsMps2GzZLGP68P8fA8OELw905lv9ZYIJ///9iuDXtLFYNMCCopMnAxC/Fg1MB88dfDHy60gyfLj9l+M/7i4FdiJGB8f/////frNZj+HjtBYYGZMVSziEMXPpzGBgfPHn7X15aiOHbxRRUd3/5xvB6zx4UxQ+fvoMEK0zTm+sz4Bp4/l1g+P/vHwMjExMDh/YMhodP3zEoyAgj4uTBk7f/cYEHT97CQxIlFpElkAGyyQBlM4mN8VpZGwAAAABJRU5ErkJggg==";
            break;
        case "Club Sandwich":
            ImageData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAAXNSR0IArs4c6QAAAOdJREFUGJV9yrFKQlEcwOHf/3ju1cKQCtEyoZpKrkmLTTq1Bj5BSy1OvoBzD9DSUg/QE+RQS0HhEGV3qCmSEMTFRFC7CaehQZBj3/xJrVIiub1OyNHGnY9g48Riou8WxhReP8zOQQGdTFtj138xqrcBJ6sjyp0bxu1PawRQw4yYtZxm5XTz36y2nkUOrzT5rzrFi9zMrLJvCoDd4yyLrWtrDgYjpFYpEZ5z+R4GJpFe4uncp5va5/aoQbnuAnC2FyAAs3Kj6uNEhEzV+4u2/HDZJxr3WHbDNFuPkzidAd7vHaJxD/XTl19s0WEy3j+GGwAAAABJRU5ErkJggg==";
            break;
        case "Mushroom Jacket Potatoes":
            ImageData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAAJCAYAAADkZNYtAAAAmElEQVQoFWNgQANrzaT+wzCaFIILU2CvYfS/xN7yv1qME3ZNIIUgBSCFWjk+YBrEh7FB8mBjQYwny4rApoBMAymCaYSZDpNnACm+XuYM1wAzHaQBZhBIHmx6sZ3l/31e+v9PJ1iCNYEEQRpghoDEQfIgdQwwxSABEIaZAqJhYnDFIIeDNCBrApkKUwiTQ4QblAWTQKaRFQEAKT2erLxgiMYAAAAASUVORK5CYII=";
            break;
        case "Sunflower Crunch":
            ImageData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAAJFBMVEUAAAAtGx5AJiv/63lcNz3+52Hp0kytlxL+rjTxoSf/7ojMtzu25Ya7AAAAAXRSTlMAQObYZgAAADVJREFUCNdjYBAUFGBgYEw3XsjAIBEWbarAIFlaZqzAIDijPckBKKnkAiZVFBgYBYWUGCDqAeUpB37bPOX0AAAAAElFTkSuQmCC";
            break;
        case "Bumpkin Roast":
            ImageData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAYAAABWdVznAAABBElEQVQoFWNgGBrATt3wPwhjcy0TsuCB03fACk3FORhAGKQJBJDVgDWAJECK62JCwQpPv/wBVgPSZK9hxLDPSx+ukQmkGCTxrz6YYdWEVAZXQ3GwJpAOEBsELHU+M/xfb8oA0sUIdsbjCIafJ94x6D9TYDgUHcJwYccusEIDDzeGsEubGKqecTC07XjIcPDGOQYWkMyzH3YMUhaHGC6eeMCgv3QNWDGIkAAqbjj4nEEtxpmhCirKdPrCDYY7qlkMh2RXMLhv5GfwffQd6GYDMA1S3HCXCSzvPmE9Q8+crQyMII3ds7eAQ8LUQANqDioFMhQESlN9GMEaYNIwjTA+jAYphLEBvj1tIcwpN2oAAAAASUVORK5CYII=";
            break;
        case "Goblin Brunch":
            ImageData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAYAAABWdVznAAAA/0lEQVQoFWNgGGbgwOk7/z9X1v/fFtbzHxkge5MRxAEp1FcRYWB8W8pwuEKVYfvLZwzm70+C1Rn5CDC8u/2BwW7NMQZGIAAr/vnr9/8fj1P/v3n77n+WbcH/hTqW/1/f3gPGIPanCs3/u/3MwJYywaxjFJ/GUBfQxOApLsUgpfSX4UJxFUyK4f//EIYfbCFgPiPIOYZrFjIcusvLYKf8meHU9Z0M5lqfwZInr/EymGm6g+VAzpx6qJ+BsXv2lv+mBhpgBauKpoBtAEl2WO8EmwwyiLc8iMHeRJmhZ85WBrCnQZpAOmAawbqRiNMXboB5pak+QF8jAZhGJCG4QpgYAPyvghCO4enaAAAAAElFTkSuQmCC";
            break;
        case "Fruit Salad":
            ImageData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAYAAABWdVznAAABL0lEQVQoFWNgoAt4Yu3yH4RhlqHzYeJgepGa8f8X26eBMUghCMD4ILl/zxP/fy9TghvGhKw7jFOJIdMyFywU1HuBIeagHgPD8csM+26lMWRY5IA1scTePMOwWN2E4ZiQJcMeWxGG/bf5GPj2PWE4svg3WPHPE+8YNr94wnCJ5xcDyHbGA6fv/Lc3UQabau2azqD3hY3BV0KGwUltFljs//8IBs6uVjD74Jm7DAwgDSA3gqzEBUB+A8mD1LKAtLJbCDFMK/zK8KNcmWH1BkEGJ1FBBpB/jmSdYwA5SfrIXQYroLMZGAoYwBpAguwMlxnYC+0ZPOI8wdZnBHUCFb9ncD7nwnAULIJEwJz1b53J/1dXVv0HBSfICVYuaWBXwpwD0sII0wfSBGNjox1MVcBqAdH3tbrdq6+VAAAAAElFTkSuQmCC";
            break;
        default :
            ImageData = itemName
            break;
    }
    return ImageData
}
